# Site settings
title: Relatable to Programming
email: timandcamiproctor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Programming tidbits I want to comment on, write about, or just
  remember for future me.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://timproctor.github.io/about" # the base hostname & protocol for your site
twitter_username: Timandcami
github_username:  timproctor

# Build settings
markdown: kramdown

# kramdown
kramdown:
  input: GFM
